spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置类型别名所对应的包
  type-aliases-package: com.example.plus.bean
  type-enums-package: com.example.plus.enums
#      # 设置mybatisPlus统一的主键生成策略
#      id-type: auto

##设置mybatisPlus全局配置
#  global-config:
#    db-config:
#      table-prefix: t_

